---
materialsPath: "C\\:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\garrysmod\\materials\\minecraft\\"
textures:
  minecraft:
    glass_pane:
      texture: glass
    air:
      type: ignored
    acacia_door:
      type: block
      translucent: false
      texture:
        parts:
          bottom: acacia_door_bottom
          top: acacia_door_top
    acacia_fence:
      texture: acacia_planks
    acacia_fence_gate:
      texture: acacia_planks
    acacia_leaves:
      translucent: true
      texture: acacia_leaves
    acacia_log:
      texture:
        sides:
          sides: acacia_log
          top: acacia_log_top
    acacia_sapling:
      texture: sapling_acacia
    acacia_slab:
      texture: acacia_planks
    activator_rail:
      texture:
        states:
          default: rail_detector
          powered: rail_detector_powered

    andesite:
      texture: stone_andesite
    andesite_slab:
      texture: stone_andesite
    anvil:
      texture:
        states:
          - sides:
              base: anvil_base
              top: anvil_top_damaged_0
          - sides:
              base: anvil_base
              top: anvil_top_damaged_1
          - sides:
              base: anvil_base
              top: anvil_top_damaged_2
    bed:
      texture:
        parts:
          head:
            sides:
              end: bed_head_end
              side: bed_head_side
              top: bed_head_top
          feet:
            sides:
              end: bed_feet_end
              side: bed_feet_side
              top: bed_feet_top
    beetroots:
      texture:
        stages:
          - beetroots_stage_0
          - beetroots_stage_1
          - beetroots_stage_2
          - beetroots_stage_3
    birch_door:
      texture:
        parts:
          bottom: birch_door_bottom
          top: birch_door_top
    birch_fence:
      texture: birch_planks
    birch_fence_gate:
      texture: birch_planks
    birch_leaves:
      translucent: true
      texture: birch_leaves
    birch_log:
      texture:
        sides:
          sides: birch_log
          top: birch_log_top
    birch_sapling:
      texture: sapling_birch
    birch_slab:
      texture: birch_planks
    black_stained_glass:
      translucent: true

    blue_stained_glass:
      translucent: true
    bone_block:
      texture:
        sides:
          side: bone_block_side
          top: bone_block_top
    brewing_stand:
      texture:
        parts:
          base: brewing_stand_base
          stand: brewing_stand
    brown_mushroom:
      texture: mushroom_brown
    brown_stained_glass:
      translucent: true
    cactus:
      texture:
        sides:
          bottom: cactus_bottom
          side: cactus_side
          top: cactus_top
    cake:
      texture:
        sides:
          bottom: cake_bottom
          inner: cake_inner
          side: cake_side
          top: cake_top
    carrots:
      texture:
        stage:
          - carrots_stage_0
          - carrots_stage_1
          - carrots_stage_2
          - carrots_stage_3
    carved_pumpkin:
      texture:
        states:
          off:
            sides:
              front: pumpkin_face_off
              side: pumpkin_side
              top: pumpkin_top
          on:
            sides:
              front: pumpkin_face_on
              side: pumpkin_side
              top: pumpkin_top
    cauldron:
      texture:
        sides:
          bottom: cauldron_bottom
          inner: cauldron_inner
          side: cauldron_side
          top: cauldron_top
    chiseled_quartz_block:
      texture:
        sides:
          sides: quartz_block_chiseled
          top: quartz_block_chiseled_top
    cut_sandstone_slab:
      texture: cut_sandstone
    chiseled_red_sandstone_slab:
      texture:
        sides:
          bottom: red_sandstone_bottom
          sides: red_sandstone_carved
          top: red_sandstone_top
    chiseled_standstone:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone_carved
          top: sandstone_top
    chiseled_standstone_slab:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone_carved
          top: sandstone_top
    chiseled_stone_bricks:
      texture: stonebrick_carved
    chiseled_stone_bricks_slab:
      texture: stonebrick_carved
    chorus_flower:
      texture:
        state:
          dead: chorus_flower_dead
          default: chorus_flower
    chorus_plant:
      texture: chorus_plant
    clay:
      texture: clay
    coal_block:
      texture: coal_block
    coal_ore:
      texture: coal_ore
    coarse_dirt:
      texture: coarse_dirt
    cobblestone:
      texture: cobblestone
    cobweb:
      texture: web
    cocoa:
      texture:
        stages:
          - cocoa_stage_0
          - cocoa_stage_1
          - cocoa_stage_2
    comparator:
      texture:
        states:
          off: comparator_off
          on: comparator_on
    cracked_stone_bricks:
      texture: stonebrick_cracked
    cracked_stone_bricks_slab:
      texture: stonebrick_cracked
    crafting_table:
      texture:
        sides:
          front: crafting_table_front
          side: crafting_table_side
          top: crafting_table_top
    oak_stairs:
      texture: oak_planks
    cyan_concrete:
      texture: hardened_clay_stained_cyan
    cyan_stained_glass:
      translucent: true
    dark_oak_door:
      texture:
        parts:
          bottom: dark_oak_door_bottom
          top: dark_oak_door_top
    oak_door:
      texture:
        parts:
          bottom: oak_door_bottom
          top: oak_door_top
    dark_oak_fence:
      texture: dark_oak_planks
    dark_oak_fence_gate:
      texture: dark_oak_planks
    dark_oak_leaves:
      translucent: true
      texture: dark_oak_leaves
    dark_oak_log:
      texture:
        sides:
          sides: dark_oak_log
          top: dark_oak_log_top
    oak_button:
      texture: oak_planks
    oak_sign:
      texture: oak_planks
    oak_wall_sign:
      texture: oak_planks
    dark_oak_slab:
      texture: dark_oak_planks
    dark_prismarine:
      texture: prismarine_dark
    daylight_detector:
      texture:
        states:
          default:
            side: daylight_detector_side
            top: daylight_detector_inverted_top
          inverted:
            side: daylight_detector_side
            top: daylight_detector_top
    dead_bush:
      texture: deadbush
    detector_rail:
      texture:
        states:
          default: rail_activator
          powered: rail_activator_powered
    diorite:
      texture: stone_diorite
    diorite_slab:
      texture: stone_diorite
    dispenser:
      texture:
        states:
          horizontal:
            sides:
              front: dispenser_front_horizontal
          vertical:
            sides:
              front: dispenser_front_vertical
    dropper:
      texture:
        states:
          horizontal:
            sides:
              front: dropper_front_vertical
          vertical:
            sides:
              front: dropper_front_horizontal
    enchanting_table:
      texture:
        sides:
          bottom: enchanting_table_bottom
          side: enchanting_table_side
          top: enchanting_table_top
    end_portal_frame:
      texture:
        sides:
          side: endframe_side
          top: endframe_top
    end_stone_bricks:
      texture: end_bricks
    end_stone_bricks_slab:
      texture: end_bricks
    farmland:
      texture:
        stages:
          - farmland_dry
          - farmland_dry
          - farmland_dry
          - farmland_dry
          - farmland_dry
          - farmland_dry
          - farmland_dry
          - farmland_wet
    frosted_ice:
      texture:
        states:
          - frosted_ice_0
          - frosted_ice_1
          - frosted_ice_2
          - frosted_ice_3
    furnace:
      texture:
        states:
          off:
            sides:
              front: furnace_front_off
              side: furnace_side
              top: furnace_top
          on:
            sides:
              front: furnace_front_on
              side: furnace_side
              top: furnace_top
    granite:
      texture: stone_granite
    granite_slab:
      texture: stone_granite
    grass_block:
      texture:
        states:
          default:
            sides:
              side: grass_block_side
              top: grass_block_top
          snowy:
            sides:
              side: grass_block_side
              top: grass_block_snow
    grass_path:
      texture:
        sides:
          side: grass_path_side
          top: grass_path_top
    gray_concrete:
      texture: hardened_clay_stained_gray
    gray_stained_glass:
      translucent: true
    green_concrete:
      texture: hardened_clay_stained_green
    green_stained_glass:
      translucent: true
    hay_block:
      texture:
        sides:
          side: hay_block_side
          top: hay_block_top
    hopper:
      texture:
        sides:
          inside: hopper_inside
          outside: hopper_outside
          top: hopper_top

    iron_door:
      texture:
        parts:
          bottom: iron_door_bottom
          top: iron_door_top
    jukebox:
      texture:
        sides:
          side: jukebox_side
          top: jukebox_top
    jungle:
      texture:
        parts:
          bottom: jungle_door_bottom
          top: jungle_door_top
    jungle_fence:
      texture: jungle_planks
    jungle_fence_gate:
      texture: jungle_planks
    jungle_leaves:
      translucent: true
      texture: jungle_leaves
    jungle_log:
      texture:
        sides:
          sides: jungle_log
          top: jungle_log_top
    jungle_sapling:
      texture: sapling_jungle
    jungle_slab:
      texture: jungle_planks
    bell: 
      texture: bell_side # todo
    lava:
      translucent: true
      texture: lava_still
#        state:
#          still: lava_still
    light_blue_concrete:
      texture: hardened_clay_stained_light_blue
    light_blue_stained_glass:
      translucent: true
    lime_concrete:
      texture: hardened_clay_stained_lime
    lime_stained_glass:
      translucent: true
    magenta_concrete:
      texture: hardened_clay_stained_magenta
    magenta_stained_glass:
      translucent: true
    magma_block:
      texture: magma
    melon:
      texture:
        sides:
          side: melon_side
          top: melon_top
    mossy_cobblestone:
      texture: cobblestone_mossy
    mossy_stone_bricks:
      texture: stonebrick_mossy
    mossy_stone_bricks_slab:
      texture: stonebrick_mossy
    mycelium:
      texture:
        sides:
          side: mycelium_side
          top: mycelium_top
    nether_bricks:
      texture: nether_brick
    nether_bricks_slab:
      texture: nether_brick
    nether_portal:
      texture: portal
    nether_quartz_ore:
      texture: quartz_ore
    nether_wart:
      texture:
        stages:
          - nether_wart_stage_0
          - nether_wart_stage_1
          - nether_wart_stage_2
    note_block:
      texture: noteblock
    oak_fence:
      texture: oak_planks
    oak_fence_gate:
      texture: oak_planks
    oak_leaves:
      translucent: true
      texture: oak_leaves
    oak_log:
      texture:
        sides:
          sides: oak_log
          top: oak_log_top
    oak_sapling:
      texture: sapling_oak
    oak_slab:
      texture: oak_planks
    orange_concrete:
      texture: hardened_clay_stained_orange
    orange_stained_glass:
      translucent: true



    pink_concrete:
      texture: hardened_clay_stained_pink
    pink_stained_glass:
      translucent: true

    podzol:
      texture:
        sides:
          side: dirt_podzol_side
          top: dirt_podzol_top
    polished_andesite:
      texture: stone_andesite_smooth
    polished_andesite_slab:
      texture: stone_andesite_smooth
    polished_diorite:
      texture: stone_diorite_smooth
    polished_diorite_slab:
      texture: stone_diorite_smooth
    polished_granite:
      texture: stone_granite_smooth
    polished_granite_slab:
      texture: stone_granite_smooth
    potatoes:
      translucent: true
      texture:
        stages:
          - potatoes_stage_0
          - potatoes_stage_1
          - potatoes_stage_2
          - potatoes_stage_3
    powered_rail:
      translucent: true
      texture:
        states:
          default: rail_golden
          powered: rail_golden_powered
    prismarine:
      texture: prismarine_rough
    purple_concrete:
      texture: hardened_clay_stained_purple
    purple_stained_glass:
      translucent: true
    purpur_stairs: 
      texture: purpur_block
    purpur_pillar:
      texture:
        sides:
          side: purpur_pillar
          top: purpur_pillar_top
    quartz_slab:
      texture:
        sides:
          bottom: quartz_block_bottom
          side: quartz_block_side
          top: quartz_block_top
    quartz_block:
      texture:
        sides:
          bottom: quartz_block_bottom
          side: quartz_block_side
          top: quartz_block_top
    quartz_pillar:
      texture:
        sides:
          side: quartz_block_lines
          top: quartz_block_lines_top
    rail:
      texture:
        states:
          default: rail_normal
          turned: rail_normal_turned
    red_concrete:
      texture: hardened_clay_stained_red
    red_mushroom:
      translucent: true
      texture: mushroom_red
    red_nether_bricks:
      texture: red_nether_brick
    red_nether_bricks_slab:
      texture: red_nether_brick
    red_sandstone:
      texture:
        sides:
          bottom: red_sandstone_bottom
          sides: red_sandstone
          top: red_sandstone_top
    red_sandstone_slab:
      texture:
        sides:
          bottom: red_sandstone_bottom
          sides: red_sandstone
          top: red_sandstone_top
    red_stained_glass:
      translucent: true

    redstone_lamp:
      texture:
        states:
          default: redstone_lamp_off
          on: redstone_lamp_on
    redstone_torch:
      texture:
        states:
          default: redstone_torch_off
          on: redstone_torch_on
    repeater:
      texture:
        states:
          off: repeater_off
          on: repeater_on
    rose_bush:
      texture: rose
    sandstone:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone
          top: sandstone_top
    sandstone_slab:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone
          top: sandstone_top
    sea_lantern:
      texture: sea_lantern
    silver_concrete:
      texture: hardened_clay_stained_silver
    silver_stained_glass:
      translucent: true
    slime_block:
      texture: slime
    smooth_stone:
      texture: smooth_stone
    smooth_stone_slab:
      texture: 
        sides:
          side: stone_slab_side
          top: stone_slab_top
    smooth_sandstone:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: cut_sandstone
          top: sandstone_top
    smooth_sandstone_slab:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: cut_sandstone
          top: sandstone_top
    smooth_red_sandstone:
      texture:
        sides:
          bottom: red_sandstone_bottom
          sides: cut_red_sandstone
          top: red_sandstone_top
    smooth_red_sandstone_slab:
      texture:
        sides:
          bottom: red_sandstone_bottom
          sides: cut_red_sandstone
          top: red_sandstone_top
    spawner:
      texture: mob_spawner
    spruce_door:
      texture:
        parts:
          bottom: spruce_door_bottom
          top: spruce_door_top
    spruce_fence:
      texture: spruce_planks
    spruce_fence_gate:
      texture: spruce_planks
    spruce_leaves:
      translucent: true
      texture: spruce_leaves
    spruce_log:
      texture:
        sides:
          sides: spruce_log
          top: spruce_log_top
    spruce_sapling:
      texture: sapling_spruce
    spruce_slab:
      texture: spruce_planks
    stone_brick_stairs:
      texture: stone_bricks
    stone_bricks_slab:
      texture: stone_bricks
    stone_slab:
      texture: stone
        
    structure_block:
      texture:
        states:
          corner: structure_block_corner
          data: structure_block_data
          default: structure_block
          load: structure_block_load
          save: structure_block_save
    tallgrass:
      texture: tallgrass
    terracotta:
      texture: hardened_clay
    tnt:
      texture:
        sides:
          bottom: tnt_bottom
          side: tnt_side
          top: tnt_top
    wall_torch:
      translucent: true
      texture: torch
    torch:
      translucent: true
      texture: torch
    trapdoor:
      translucent: true
      texture: trapdoor
    #  tripwire:
    #    translucent: true
    #    texture: trip_wire
    #  tripwire_hook:
    #    translucent: true
    #    texture: trip_wire_source
    vine:
      translucent: true
      texture: vine
    water_still:
      translucent: true      
    water:
      translucent: true
      texture: water_still
#        state:
#          still: water_still
    waterlily:
      texture: waterlily
    wet_sponge:
      texture: sponge_wet
    wheat:
      translucent: true
      texture:
        stages:
          - wheat_stage_0
          - wheat_stage_1
          - wheat_stage_2
          - wheat_stage_3
          - wheat_stage_4
          - wheat_stage_5
          - wheat_stage_6
          - wheat_stage_7
    white_concrete:
      texture: hardened_clay_stained_white
    white_stained_glass:
      translucent: true
    yellow_concrete:
      texture: hardened_clay_stained_yellow
    yellow_stained_glass:
      translucent: true
    sandstone_wall:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone
          top: sandstone_top
    sandstone_stairs:
      texture:
        sides:
          bottom: sandstone_bottom
          sides: sandstone
          top: sandstone_top  
    chest:
      texture: oak_planks
    trapped_chest: 
      texture: oak_planks
    